Repository sswu-meets/meets, pull requests merged in 2022-08, with the labels that each got.

#31 api 명세서 정리
  src/main/java/com/sswu/meets/controller/MeetingController.java
  src/main/java/com/sswu/meets/controller/TodoController.java
  src/main/java/com/sswu/meets/controller/UserController.java
  src/main/java/com/sswu/meets/dto/MeetingResponseDto.java
  src/main/java/com/sswu/meets/dto/UserResponseDto.java
  src/main/java/com/sswu/meets/dto/UserUpdateRequestDto.java
Labels: documentation

#36 schedule date tune CRUD 구현
  src/main/java/com/sswu/meets/controller/ScheduleDateTuneController.java
  src/main/java/com/sswu/meets/controller/TodoController.java
  src/main/java/com/sswu/meets/domain/schedule/Schedule.java
  src/main/java/com/sswu/meets/domain/scheduleDateTune/ScheduleDateTuneRepository.java
  src/main/java/com/sswu/meets/domain/todo/Todo.java
  src/main/java/com/sswu/meets/domain/todo/TodoRepository.java
  src/main/java/com/sswu/meets/dto/ScheduleDateTuneResponseDto.java
  src/main/java/com/sswu/meets/dto/ScheduleResponseDto.java
  src/main/java/com/sswu/meets/dto/TodoResponseDto.java
  src/main/java/com/sswu/meets/dto/TodoUpdateRequestDto.java
  src/main/java/com/sswu/meets/service/ScheduleDateTuneService.java
  src/main/java/com/sswu/meets/service/ScheduleService.java
  src/main/java/com/sswu/meets/service/TodoService.java
Labels: feature

#29 todo crud 구현
  src/main/java/com/sswu/meets/controller/TodoController.java
  src/main/java/com/sswu/meets/domain/schedule/Schedule.java
  src/main/java/com/sswu/meets/domain/todo/Todo.java
  src/main/java/com/sswu/meets/domain/todo/TodoRepository.java
  src/main/java/com/sswu/meets/dto/ScheduleResponseDto.java
  src/main/java/com/sswu/meets/dto/TodoResponseDto.java
  src/main/java/com/sswu/meets/dto/TodoUpdateRequestDto.java
  src/main/java/com/sswu/meets/service/ScheduleService.java
  src/main/java/com/sswu/meets/service/TodoService.java
Labels: feature

#32 일정 등록 api 수정
  src/main/java/com/sswu/meets/controller/ScheduleController.java
  src/main/java/com/sswu/meets/controller/ScheduleDateFixController.java
  src/main/java/com/sswu/meets/controller/ScheduleDateTuneController.java
  src/main/java/com/sswu/meets/domain/schedule/Schedule.java
  src/main/java/com/sswu/meets/domain/scheduleDateFix/ScheduleDateFix.java
  src/main/java/com/sswu/meets/domain/scheduleDateFix/ScheduleDateFixRepository.java
  src/main/java/com/sswu/meets/dto/FixScheduleSaveRequestDto.java
  src/main/java/com/sswu/meets/dto/ScheduleDateFixSaveRequestDto.java
  src/main/java/com/sswu/meets/dto/ScheduleSaveRequestDto.java
  src/main/java/com/sswu/meets/dto/TuneScheduleSaveRequestDto.java
  src/main/java/com/sswu/meets/service/ScheduleDateFixService.java
  src/main/java/com/sswu/meets/service/ScheduleDateTuneService.java
  src/main/java/com/sswu/meets/service/ScheduleService.java
Labels: enhancement

#37 Feat/remove user no in api/youjung
  src/main/java/com/sswu/meets/config/auth/CustomOAuth2UserService.java
  src/main/java/com/sswu/meets/config/auth/dto/OAuthAttributes.java
  src/main/java/com/sswu/meets/config/auth/dto/SessionUser.java
  src/main/java/com/sswu/meets/controller/MeetingController.java
  src/main/java/com/sswu/meets/domain/user/User.java
  src/main/java/com/sswu/meets/dto/MeetingSaveRequestDto.java
  src/main/java/com/sswu/meets/dto/UserResponseDto.java
  src/main/java/com/sswu/meets/dto/UserSaveRequestDto.java
  src/main/java/com/sswu/meets/dto/UserUpdateRequestDto.java
  src/main/java/com/sswu/meets/service/MeetingService.java
  src/main/java/com/sswu/meets/service/UserService.java
Labels: enhancement

#38 유저가 참여하고 있는 모든 모임 조회
  src/main/java/com/sswu/meets/controller/MeetingController.java
  src/main/java/com/sswu/meets/controller/UserController.java
  src/main/java/com/sswu/meets/dto/MeetingResponseDto.java
  src/main/java/com/sswu/meets/service/MeetingService.java
  src/main/java/com/sswu/meets/service/UserService.java
Labels: feature

#39 탈퇴하기와 유저 정보 수정하기 api에서 user_no 제거
  src/main/java/com/sswu/meets/controller/UserController.java
Labels: enhancement

#42 todoContent, todoStatus 부분 수정되도록 코드 변경
  src/main/java/com/sswu/meets/controller/TodoController.java
  src/main/java/com/sswu/meets/domain/todo/Todo.java
  src/main/java/com/sswu/meets/service/TodoService.java
Labels: enhancement

#47 날짜&시간 조율 등록 기능 추가
  src/main/java/com/sswu/meets/controller/AvTimeController.java
  src/main/java/com/sswu/meets/controller/DateTuneController.java
  src/main/java/com/sswu/meets/controller/TuneTimeController.java
  src/main/java/com/sswu/meets/domain/avTime/AvTime.java
  src/main/java/com/sswu/meets/domain/avTime/AvTimeRepository.java
  src/main/java/com/sswu/meets/domain/dateTune/DateTune.java
  src/main/java/com/sswu/meets/domain/dateTune/DateTuneRepository.java
  src/main/java/com/sswu/meets/domain/schedule/Schedule.java
  src/main/java/com/sswu/meets/domain/tuneTime/TuneTime.java
  src/main/java/com/sswu/meets/domain/tuneTime/TuneTimeRepository.java
  src/main/java/com/sswu/meets/dto/DateTuneSaveRequestDto.java
  src/main/java/com/sswu/meets/service/AvTimeService.java
  src/main/java/com/sswu/meets/service/DateTuneService.java
  src/main/java/com/sswu/meets/service/ScheduleService.java
  src/main/java/com/sswu/meets/service/TuneTimeService.java
Labels: feature

#49 best3 결과 조회 api 추가
  src/main/java/com/sswu/meets/controller/TuneTimeController.java
  src/main/java/com/sswu/meets/domain/tuneTime/TuneTimeRepository.java
  src/main/java/com/sswu/meets/dto/Best3ResponseDto.java
  src/main/java/com/sswu/meets/service/ScheduleService.java
  src/main/java/com/sswu/meets/service/TuneTimeService.java
Labels: feature

#56 로그인 api 수정
  src/main/java/com/sswu/meets/config/WebConfig.java
  src/main/java/com/sswu/meets/config/auth/LoginSuccessHandler.java
  src/main/java/com/sswu/meets/config/auth/LoginUser.java
  src/main/java/com/sswu/meets/config/auth/LoginUserArgumentResolver.java
  src/main/java/com/sswu/meets/config/auth/Security.java
  src/main/java/com/sswu/meets/controller/UserController.java
Labels: enhancement

#51 유저가 참여하고 있는 일정 조회 구현
  src/main/java/com/sswu/meets/controller/ScheduleController.java
  src/main/java/com/sswu/meets/controller/UserController.java
  src/main/java/com/sswu/meets/domain/attendance/Attendance.java
  src/main/java/com/sswu/meets/domain/attendance/AttendanceRepository.java
  src/main/java/com/sswu/meets/domain/schedule/Schedule.java
  src/main/java/com/sswu/meets/domain/user/User.java
  src/main/java/com/sswu/meets/service/ScheduleService.java
  src/main/java/com/sswu/meets/service/UserService.java
Labels: feature
